### ISSUE TITLE
Bing translation?

### ISSUE THREAD

**Issue by net1313** [e107translations/French#4]
define("LAN_RE_ORDER", "Re-commander"); 

Vous traduisez ça comme "Re-commander" ?
Peut être un peu plus de vigilance dans la traduction ferait du bien.

**Comment by OTroccaz** [comment]
Bonjour tout d'abord !
J'ai repris les traductions là où elles en étaient et n'ai effectivement pas vérifié tous les fichiers !!! Si vous êtes si à l'aise, ne vous gênez pas ... mais je suis assez surpris de ce genre d'agressivité au sein de la communauté e107. Décevant !

**Comment by net1313** [comment]
Hmm, désolé de heurter votre ego fragile. Il n'y avait pas un soupçon d'agressivité dans mes propos. Juste une question - traduction via Bing ou non.

Je pars du principe que le travail doit être fait correctement. Surtout si on veut promouvoir e107.
Car ce dernier a souffert de manque de publicité alors que il est très bon parmi les moteurs gratuits.
Avant de traduire j'installe e107 et j'essaie de voir si l'administration de e107 (afin, la traduction) est compréhensible pour l'utilisateur final.
Peu importe, la traduction mot à mot ou juste le sense de la phrase. L'essentiel est q'utilisateur soit à l'aise.

> ...Si vous êtes si à l'aise, ne vous gênez pas....

Je fait la traduction du e107 en russe.
Croyez moi, cette langue inadaptée est chiante pour traduire correctement en utilisant la terminologie informatique.
Là, ou en anglais ou français, un ou deux mots sont suffisants, il faut construire un paragraphe en russe.
Donc une vraie casse tête pour rentrer la brève description dans le cadre d'administration du système.

Et quand je voie (et ça saute aux yeux) "Re order" traduit comme "recommander" au lieu de "réorganiser", c'est normal que je pose la question concernant la traduction.

ça n'a rien avoir avec la communauté. Par ailleurs, si vous considérez que la communauté est le monde de bisounours, vous vous trompez.

Encore une fois désolé si mes propos ont été interprété incorrectement.

**Comment by OTroccaz** [comment]
Vous êtes une exception : je n'ai jamais eu aucun problème avec les autres membres de la communauté. Désolé !
