### ISSUE TITLE
Caractères spéciaux en Français

### ISSUE THREAD

**Issue by ericc-dream** [e107translations/French#5]
Bonjour 

Tout d'abord je tiens à vous remercier du travail accompli pour traduire e107 en français. C'est très apprécié de mes utilisateurs 

Cependant, j'ai une remarque parce que j'ai trouvé un petit soucis 
Dans des strings qui doivent s'afficher dans une page html, il est conseillé de remplacer les caractères spéciaux (les apostrophes, les lettres accentués ...etc) par des "HTML entities" 
[https://dev.w3.org/html5/html-author/charref](url)

Par exemple: 
v2/e107_plugins/login_menu/languages/French.php
`define("LAN_LOGINMENU_50", "Nom d'utilisateur ou mail : ");`
cette string est utilisé dans le menu de login. Elle est affiché au dessus du champ (input), et à cet endroit pas de problème, mais aussi **dans** le champ de saisie (placeholder) et à cet endroit, elle n'affiche que "Nom d" 
, l'apostrophe étant mal interprété par le navigateur (ou PHP, pas sûr)
En fait c'est même pire parce que si on regarde le code, cela donne 
`<input class="form-control tbox login user" type="text" name="username" placeholder="Nom d" utilisateur="" ou="" mail="" :="" '="" required="required" id="username" size="15" value="" maxlength="100">`

j'ai peur que dans certaines circonstances, cela ne pose des problèmes ! 

Il aurait fallu définir la string comme ceci 
`define("LAN_LOGINMENU_50", "Nom d&apos;utilisateur ou mail : ");`
l'apostrophe étant remplacé par son équivalent qui fonctionne partout ... 
Il existe des plugins sur certains éditeurs qui permettent de remplacer automatiquement les caractères spéciaux ... 

ericc

**Comment by OTroccaz** [comment]
Bonjour,
Merci de votre message.
Vous avez raison, mais beaucoup de fichiers étaient déjà traduits lorsque j'ai découvert e107 et je les ai pris tels quels ... et il y en a quelques uns ! Il faudrait que je prenne le temps de les vérifier mais, honnêtement, j'essaye de suivre les traductions assez régulièrement mais ne peut pas y consacrer trop de temps.
Par contre, effectivement, je vais corriger ces problèmes d'apostrophes car ça peut être vraiment gênant pour l'interprétation PHP.
Olivier

**Comment by ericc-dream** [comment]
Avec Netbeans, il y a un plugin pour convertir automatiquement 
Tu sélectionne la string, puis tu sélectionne dans le menu ou la toolbar si tu as mis l'icone ou le raccourci clavier "Alt+F12"
Notepad++ possède aussi ce genre de plugin
C'est bien pratique et permet de gagner pas mal de temps ....
Normalement avec le support de l'UTF8 cela ne devrait plus être nécessaire mais ce n'est pas le cas partout ... contrairement aux entities qui elles fonctionnent dans tout les cas (et le support des langues dans e107, ce n'est pas le top, soit dit en passant)
ericc

**Comment by OTroccaz** [comment]
Merci !
Avec le nombre total de fichiers langue du noyau, des thèmes et des extensions, je vais voir à écrire un petit script qui va tout parcourir et remplacer ce qui doit l'être. Je ne me vois pas trop ouvrir chaque fichier l'un après l'autre ...
Olivier

**Comment by OTroccaz** [comment]
Bonjour,
J'ai donc encodé tous les caractères accentués et apostrophes : il ne devrait plus y avoir de problème désormais.
Olivier
